# Generated by Django 4.0.6 on 2023-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas_orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='interes',
            field=models.ManyToManyField(related_name='interes', to='personas_orm.interes'),
        ),
    ]
