# Generated by Django 4.0.6 on 2023-02-20 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes_orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('nom_area', models.CharField(max_length=150, verbose_name='Area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('nom_est', models.CharField(max_length=150, verbose_name='Area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ap', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('am', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto')),
                ('Carrera', models.CharField(choices=[('Sistemas', 'Sistemas'), ('Contabilidad', 'Contabilidad'), ('Derecho', 'Derecho'), ('Adminsitracion', 'Administracion'), ('Diseño', 'Diseño'), ('Ingeniero', 'Ingeniero'), ('General', 'General')], max_length=100, verbose_name='Carrera')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_orm.area', verbose_name='Area')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_orm.estudio', verbose_name='Estudio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
